language: ruby
before_install:
- travis_retry gem install jekyll
- sudo rm /etc/apt/sources.list.d/git-ppa-source.list
- sudo apt-get remove git && sudo apt-get remove git-man && sudo apt-get install git-man && sudo apt-get install git
script: jekyll build
deploy:
  provider: openshift
  user: eschultz@outercurve.org
  password:
    secure: iho3XGKrGAcXg5QH0PnmXFoNomcCHBLuYqicSqG4mrHqBS4rPRxCZDy+MWzrXizElzDIiUnfP/ZpPGVlgK0bmgMt7IJWhUe7f2kn70sRzHdIci1TBSBpc4R5kE/kH4MOjn/33+PmXy/q9lpXcFCt4c9MvV30CpV2oCgekhBTz1w=
  domain: outercurve
  skip_cleanup: true
  deployment_branch: release
  app: root
  on:
    branch: release
