language: ruby
before_install:
- travis_retry gem install jekyll
- wget http://launchpadlibrarian.net/101227100/git-man_1.7.9.5-1_all.deb && sudo dpkg -i git-man_1.7.9.5-1_all.deb
- wget http://launchpadlibrarian.net/101225632/git_1.7.9.5-1_amd64.deb && sudo dpkg -i git_1.7.9.5-1_amd64.deb
script: jekyll build
deploy:
  provider: openshift
  user: eschultz@outercurve.org
  password:
    secure: iho3XGKrGAcXg5QH0PnmXFoNomcCHBLuYqicSqG4mrHqBS4rPRxCZDy+MWzrXizElzDIiUnfP/ZpPGVlgK0bmgMt7IJWhUe7f2kn70sRzHdIci1TBSBpc4R5kE/kH4MOjn/33+PmXy/q9lpXcFCt4c9MvV30CpV2oCgekhBTz1w=
  domain: outercurve
  app: jekylltest
  on:
    branch: new_test
