language: ruby
before_install:
- travis_retry gem install jekyll
script: jekyll build
deploy:
  provider: heroku
  api_key:
    secure: C8ose4cx3uCwCRih1ZVQCml+VGnxrWePC+h7ZeWzKkEsDGHYRQEPD3oeHgcjKPAm8qWVNQyedktgGtaEGFptkF++IieAX/f8gLLhIpGYMBNDGY2qhH/LAJX8Cj1wcG0Qkt9VTaFUkfqWz2g/En2X2jsxClR05+F3t+W6Us07sC0=
  app: frozen-lake-3397
  on:
    repo: ericschultz/flaming-ninja
